includes:
- ./traced_caption.yaml

dataset_config:
  caption_coco2017:
    annotations:
      train:
      - localized_narratives/defaults/annotations/bbox_aligned_dev/coco_train_localized_narratives-00000-of-00004.jsonl
      - localized_narratives/defaults/annotations/bbox_aligned_dev/coco_train_localized_narratives-00001-of-00004.jsonl
      - localized_narratives/defaults/annotations/bbox_aligned_dev/coco_train_localized_narratives-00002-of-00004.jsonl
      - localized_narratives/defaults/annotations/bbox_aligned_dev/coco_train_localized_narratives-00003-of-00004.jsonl
      val:
      - localized_narratives/defaults/annotations/bbox_aligned_dev/coco_val_localized_narratives.jsonl
      test:
      - localized_narratives/defaults/annotations/bbox_aligned_dev/coco_val_localized_narratives.jsonl
