dataset_config:
  caption_coco2017:
    data_dir: ${env.data_dir}/datasets
    use_images: False
    use_features: True
    zoo_requirements:
    - coco.defaults
    features:
      train:
      - coco/defaults/features/coco_train2017_ln.lmdb
      val:
      - coco/defaults/features/coco_val2017_ln.lmdb
      test:
      - coco/defaults/features/coco_val2017_ln.lmdb
    annotations:
      train:
      - localized_narratives/defaults/annotations/coco_train_localized_narratives.lmdb
      val:
      - localized_narratives/defaults/annotations/coco_val_localized_narratives.lmdb
      test:
      - localized_narratives/defaults/annotations/coco_val_localized_narratives.lmdb
    processors:
      caption_processor:
        type: traced_bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: True
          max_seq_length: 64
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
      trace_bbox_processor:
        type: spatial_trace_tokenizer
        params:
          max_seq_length: 64
          delta: 0.1
          reverse: false
