includes:
  - ../../../../mmf/configs/datasets/coco2017/traced_caption_dev.yaml

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: 11000

training:
  evaluation_interval: 10
  checkpoint_interval: 10
  log_interval: 10
  clip_norm_mode: all
  clip_gradients: true
  max_grad_l2_norm: 0.25
  use_warmup: true
  warmup_factor: 0.2
  warmup_iterations: 1000
  batch_size: 32
  lr_scheduler: true
  num_workers: 0
  # Don't forget to update schedule_attributes if you update this
  max_updates: 88000
  find_unused_parameters: true
  early_stop:
    criteria: val/caption_coco2017/traced_bert_caption_bleu4
    minimize: false
evaluation:
  metrics:
    - traced_bert_caption_bleu4
